FROM resin/armv7hf-debian:stretch
#FROM resin/armv7hf-debian-qemu

RUN [ "cross-build-start" ]

RUN apt-get update && \
    apt-get install -y python3 python3-setuptools python3-pip && \
    mkdir /opt/api && \
    apt-get clean && \
    rm -Rf /var/lib/apt/lists

COPY . /opt/api/

WORKDIR /opt/api

RUN pip3 install wheel && \
    pip3 install -r requirements.txt

RUN [ "cross-build-end" ]

CMD ["python3", "run.py"]


